# 使用官方OpenJDK运行时
FROM eclipse-temurin:17.0.18_8-jdk-noble

# 设置工作目录
WORKDIR /data/app

# 复制本地打包好的JAR文件到容器
COPY target/livepulse-connector-wechat-mp-open.jar app.jar

# 暴露端口
EXPOSE 23014

# 设置 JVM 参数和 Spring Boot 启动参数 服务器上这些参数配置在 .env 文件中 防止容器push时暴漏密码
ARG JAVA_OPTS
ARG SPRING_PROFILES_ACTIVE
ARG SPRING_CLOUD_NACOS_SERVER_ADDR
ARG SPRING_CLOUD_NACOS_CONFIG_GROUP
ARG SPRING_CLOUD_NACOS_DISCOVERY_GROUP
ARG SPRING_CLOUD_NACOS_CONFIG_NAMESPACE
ARG SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
ARG SPRING_CLOUD_NACOS_USERNAME
ARG SPRING_CLOUD_NACOS_PASSWORD

ENV ARG JAVA_OPTS=${JAVA_OPTS}
ENV ARG SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV ARG SPRING_CLOUD_NACOS_SERVER_ADDR=${SPRING_CLOUD_NACOS_SERVER_ADDR}
ENV ARG SPRING_CLOUD_NACOS_CONFIG_GROUP=${SPRING_CLOUD_NACOS_CONFIG_GROUP}
ENV ARG SPRING_CLOUD_NACOS_DISCOVERY_GROUP=${SPRING_CLOUD_NACOS_DISCOVERY_GROUP}
ENV ARG SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=${SPRING_CLOUD_NACOS_CONFIG_NAMESPACE}
ENV ARG SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=${SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE}
ENV ARG SPRING_CLOUD_NACOS_USERNAME=${SPRING_CLOUD_NACOS_USERNAME}
ENV ARG SPRING_CLOUD_NACOS_PASSWORD=${SPRING_CLOUD_NACOS_PASSWORD}


# 构建完整的启动命令（前台运行，不使用 nohup/&）
#CMD [\"sh\", \"-c\", \"java $JAVA_OPTS \\
#  -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE \\
#  -Dspring.cloud.nacos.server-addr=$SPRING_CLOUD_NACOS_SERVER_ADDR \\
#  -Dspring.cloud.nacos.discovery.server-addr=$SPRING_CLOUD_NACOS_SERVER_ADDR \\
#  -Dspring.cloud.nacos.config.group=$SPRING_CLOUD_NACOS_CONFIG_GROUP \\
#  -Dspring.cloud.nacos.discovery.group=$SPRING_CLOUD_NACOS_DISCOVERY_GROUP \\
#  -Dspring.cloud.nacos.config.namespace=$SPRING_CLOUD_NACOS_CONFIG_NAMESPACE \\
#  -Dspring.cloud.nacos.discovery.namespace=$SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE \\
#  -Dspring.cloud.nacos.username=$SPRING_CLOUD_NACOS_USERNAME \\
#  -Dspring.cloud.nacos.password=$SPRING_CLOUD_NACOS_PASSWORD \\
#  -jar app.jar\"]

CMD [\"sh\", \"-c\", \"java $JAVA_OPTS \\
  -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE \\
  -DNACOS_HOST=$SPRING_CLOUD_NACOS_SERVER_ADDR \\
  -DNACOS_NAMESPACE=$SPRING_CLOUD_NACOS_CONFIG_GROUP \\
  -DNACOS_PORT=8848 \\
  -Dspring.cloud.nacos.discovery.group=$SPRING_CLOUD_NACOS_DISCOVERY_GROUP \\
  -Dspring.cloud.nacos.config.group=$SPRING_CLOUD_NACOS_CONFIG_NAMESPACE \\
  -DNACOS_USERNAME=$SPRING_CLOUD_NACOS_USERNAME \\
  -DNACOS_PASSWORD=$SPRING_CLOUD_NACOS_PASSWORD \\
  -jar app.jar\"]
